package workspace

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

func TestImpactGraphUsesLanguageEdgesAndDisclosesUncertaintyAndVariants(t *testing.T) {
	root := t.TempDir()
	files := map[string]string{
		"src/value.ts":       "export const value = 1\n",
		"src/use.ts":         "import { value } from './value'\nexport const used = value\n",
		"src/use.test.ts":    "import { used } from './use'\nconsole.log(used)\n",
		"src/dynamic.ts":     "export const lazy = import(variable)\n",
		"generated/api.go":   "// Code generated by tool. DO NOT EDIT.\npackage generated\n",
		"schema/config.json": "{}\n",
	}
	for name, content := range files {
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		writeFile(t, path, content)
	}
	graph, err := BuildImpactGraph(root, "prep_graph", []string{"src/value.ts", "schema/config.json"}, ImpactPolicy{}, []VariantPolicy{
		{Name: "linux", Files: []string{"src/**"}, Required: true},
		{Name: "windows", Files: []string{"windows/**"}, Required: true},
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{"src/value.ts", "src/use.ts", "src/use.test.ts"} {
		if !containsString(graph.Affected, path) {
			t.Fatalf("affected %v does not include %s", graph.Affected, path)
		}
	}
	if !containsString(graph.Adapters, "typescript") {
		t.Fatalf("adapters = %v", graph.Adapters)
	}
	if !containsString(graph.Included, "linux") || !containsString(graph.Omitted, "windows") {
		t.Fatalf("variants included=%v omitted=%v", graph.Included, graph.Omitted)
	}
	for _, kind := range []string{"dynamic_or_reflection", "generated_code", "configuration", "variant_omitted"} {
		if !hasImpactRisk(graph.Risks, kind) {
			t.Fatalf("risks = %+v; missing %s", graph.Risks, kind)
		}
	}
	if graph.Coverage.Complete || !graph.RecommendFull {
		t.Fatalf("uncertain graph = %+v", graph)
	}
}

func TestImpactGraphCapsAreExplicit(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "a.ts"), "export const a = 1\n")
	writeFile(t, filepath.Join(root, "b.ts"), "import { a } from './a'\n")
	graph, err := BuildImpactGraph(root, "rev_cap", []string{"a.ts"}, ImpactPolicy{MaxFiles: 1, MaxEdges: 1}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if !graph.Coverage.Capped || !hasImpactRisk(graph.Risks, "graph_cap") || graph.Coverage.Complete {
		t.Fatalf("capped graph = %+v", graph)
	}
}

func TestAffectedTestsAreAdvisoryRevisionKeyedAndNeverSetFullGate(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("shell fixture is POSIX-specific")
	}
	sandbox, prepared := pipelineSandbox(t, map[string]string{
		"src/value.ts":    "export const value = 1\n",
		"src/use.ts":      "import { value } from './value'\n",
		"src/use.test.ts": "import './use'\n",
	})
	policy := trustedPolicy(t, sandbox.Tree)
	policy.Tests = []CommandPolicy{
		{Name: "unit", Command: []string{"sh", "-c", "test -f src/use.test.ts"}, Covers: []string{"src/**"}, Variants: []string{"node20"}},
		{Name: "release", Command: []string{"sh", "-c", "exit 9"}, Covers: []string{"release/**"}},
	}
	policy.Variants = []VariantPolicy{{Name: "node20", Files: []string{"src/**"}, Required: true}}
	history := filepath.Join(t.TempDir(), "history.json")
	result, err := RunVerificationPipeline(context.Background(), sandbox, policy, VerificationRequest{
		Revision: "prep_targeted", Stages: []string{"tests"}, TestScope: "affected", TestHistoryPath: history,
	}, []PlanStageFile{preparedFile(t, prepared, "src/value.ts")})
	if err != nil {
		t.Fatal(err)
	}
	if result.Targeted == nil || result.Targeted.Status != "affected_tests_passed" {
		t.Fatalf("targeted = %+v", result.Targeted)
	}
	if result.FullTestGate != "" {
		t.Fatalf("targeted run changed full gate: %q", result.FullTestGate)
	}
	if len(result.Stages) != 1 || result.Stages[0].TestVerdict != "affected_tests_passed" || len(result.Stages[0].ExecutedTests) != 1 || result.Stages[0].ExecutedTests[0] != "unit" {
		t.Fatalf("stages = %+v", result.Stages)
	}
	content, err := os.ReadFile(history)
	if err != nil {
		t.Fatal(err)
	}
	var state testHistoryState
	if err := json.Unmarshal(content, &state); err != nil {
		t.Fatal(err)
	}
	if len(state.Entries) != 1 || state.Entries[0].Revision != "prep_targeted" || state.Entries[0].Scope != "affected" {
		t.Fatalf("history = %+v", state)
	}

	full, err := RunVerificationPipeline(context.Background(), sandbox, policy, VerificationRequest{
		Revision: "prep_full", Stages: []string{"tests"}, TestScope: "full", TestHistoryPath: history,
	}, prepared)
	if err == nil {
		t.Fatal("full suite unexpectedly passed")
	}
	if full.FullTestGate != "full_tests_failed" || full.Targeted != nil {
		t.Fatalf("full result = %+v", full)
	}
}

func TestAffectedSelectionWithoutAssociationIsUnavailableNotClean(t *testing.T) {
	sandbox, prepared := pipelineSandbox(t, map[string]string{"main.go": "package main\n"})
	policy := trustedPolicy(t, sandbox.Tree)
	policy.Tests = []CommandPolicy{{Name: "unrelated", Command: []string{"false"}, Covers: []string{"web/**"}}}
	result, err := RunVerificationPipeline(context.Background(), sandbox, policy, VerificationRequest{
		Revision: "prep_none", Stages: []string{"tests"}, TestScope: "affected",
	}, prepared)
	if err != nil {
		t.Fatal(err)
	}
	if result.Targeted == nil || result.Targeted.Status != "unavailable" || len(result.Stages) != 1 || result.Stages[0].Status != VerificationSkipped {
		t.Fatalf("result = %+v", result)
	}
}

func TestAffectedSelectionIncludesRevisionKeyedPriorFailure(t *testing.T) {
	graph := ImpactGraph{Affected: []string{"src/value.go"}}
	tests := []CommandPolicy{{Name: "integration", Command: []string{"go", "test", "./integration"}, Covers: []string{"integration/**"}}}
	selected := SelectAffectedTests(graph, tests, []TestHistoryEntry{{Revision: "rev_previous", Test: "integration", Status: string(VerificationFailed)}})
	if len(selected) != 1 || !containsString(selected[0].Reasons, "prior_failure") {
		t.Fatalf("selected = %+v", selected)
	}
}

func preparedFile(t *testing.T, files []PlanStageFile, path string) PlanStageFile {
	t.Helper()
	for _, file := range files {
		if file.Path == path {
			return file
		}
	}
	t.Fatalf("missing prepared file %s", path)
	return PlanStageFile{}
}

func hasImpactRisk(risks []ImpactRisk, kind string) bool {
	for _, risk := range risks {
		if risk.Kind == kind {
			return true
		}
	}
	return false
}
