// Code generated by the fixture generator. DO NOT EDIT.

package huyangfixture

// GeneratedNames exists so an impact preview has a generated file to notice.
var GeneratedNames = []string{"total", "unused"}
